
spring:
  # MySQL properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring_security?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  # Hibernate properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true