version: "3.8"
name: spring-boot-security-demo

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spring_security
    ports:
      - "3307:3306"